"""Modbus register definitions for all Schneider Conext device types.

Based on official Schneider Electric Modbus Maps:
- 503-0246-01-01_RevA.4 (XW/XW+ Device)
- 503-0252-01-01_RevA.4 (MPPT 80 Device)
- 503-0248-01-01_RevA.4 (MPPT 60 Device)
- 503-0247-01-01_RevA.4 (AGS Device)
- 503-0261-01-01_RevA.4 (Battery Monitor Device)
- IH-IF-Gateway Modbus Maps (Gateway/InsightHome/InsightFacility)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)


class RegisterType(Enum):
    """Modbus register type."""
    INPUT = "input"
    HOLDING = "holding"


class DataType(Enum):
    """Modbus data type."""
    UINT16 = "uint16"
    INT16 = "int16"
    UINT32 = "uint32"
    INT32 = "int32"
    FLOAT32 = "float32"
    STRING = "string"


@dataclass
class ModbusRegisterDefinition:
    """Definition of a single Modbus register."""
    name: str
    key: str
    address: int
    register_type: RegisterType
    data_type: DataType
    count: int = 1
    scale: float = 1.0
    precision: int = 0
    unit: str | None = None
    device_class: str | None = None
    state_class: str | None = None
    writable: bool = False
    min_value: float | None = None
    max_value: float | None = None
    options: dict[int, str] | None = None
    icon: str | None = None
    entity_category: str | None = None


# =============================================================================
# XW PRO INVERTER/CHARGER REGISTERS (slave default: 10)
# Based on 503-0246-01-01_RevA.4_Modbus_Map_Conext_XW_Device.pdf
# =============================================================================

XW_PRO_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    # --- Device Info ---
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
    ModbusRegisterDefinition(
        name="Device Status",
        key="device_status",
        address=50,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:state-machine",
        options={
            1: "Invert",
            2: "AC Pass Through",
            3: "APS Only",
            4: "Load Sense",
            5: "Inverter Disabled",
            6: "Load Sense Ready",
            7: "Engaging Inverter",
            8: "Invert Fault",
            9: "Inverter Standby",
            10: "Grid-Tied",
            11: "Grid Support",
            12: "Gen Support",
            13: "Sell-to-Grid",
            14: "Load Shaving",
            15: "Grid Frequency Stabilization",
        },
    ),
    ModbusRegisterDefinition(
        name="Active Faults",
        key="active_faults",
        address=52,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        icon="mdi:alert-circle",
        entity_category="diagnostic",
    ),
    ModbusRegisterDefinition(
        name="Active Warnings",
        key="active_warnings",
        address=54,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        icon="mdi:alert",
        entity_category="diagnostic",
    ),
    # --- Battery ---
    ModbusRegisterDefinition(
        name="Battery Voltage",
        key="battery_voltage",
        address=80,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    ModbusRegisterDefinition(
        name="Battery Current",
        key="battery_current",
        address=82,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=3,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    ModbusRegisterDefinition(
        name="Battery Power",
        key="battery_power",
        address=84,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    ModbusRegisterDefinition(
        name="Battery Temperature",
        key="battery_temperature",
        address=86,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    ModbusRegisterDefinition(
        name="Battery SOC",
        key="battery_soc",
        address=88,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=1.0,
        precision=0,
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart-variant",
    ),
    # --- AC Input (Grid/Generator) ---
    ModbusRegisterDefinition(
        name="AC Input Voltage L1",
        key="ac_input_voltage_l1",
        address=90,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=1,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Input Voltage L2",
        key="ac_input_voltage_l2",
        address=92,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=1,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Input Current",
        key="ac_input_current",
        address=94,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Input Power",
        key="ac_input_power",
        address=96,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower",
    ),
    ModbusRegisterDefinition(
        name="AC Input Frequency",
        key="ac_input_frequency",
        address=98,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=0.01,
        precision=2,
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    # --- AC Output (Load) ---
    ModbusRegisterDefinition(
        name="AC Output Voltage L1",
        key="ac_output_voltage_l1",
        address=100,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=1,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Output Voltage L2",
        key="ac_output_voltage_l2",
        address=102,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=1,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Output Current",
        key="ac_output_current",
        address=104,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="AC Output Power",
        key="ac_output_power",
        address=106,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:home-lightning-bolt",
    ),
    ModbusRegisterDefinition(
        name="AC Output Frequency",
        key="ac_output_frequency",
        address=108,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=0.01,
        precision=2,
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ModbusRegisterDefinition(
        name="Load Power",
        key="load_power",
        address=110,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    # --- Energy Counters ---
    ModbusRegisterDefinition(
        name="Total Energy from Grid",
        key="total_energy_from_grid",
        address=120,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:transmission-tower-import",
    ),
    ModbusRegisterDefinition(
        name="Total Energy to Grid",
        key="total_energy_to_grid",
        address=122,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:transmission-tower-export",
    ),
    ModbusRegisterDefinition(
        name="Total Load Energy",
        key="total_load_energy",
        address=124,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:lightning-bolt",
    ),
    # --- Charger ---
    ModbusRegisterDefinition(
        name="Charger State",
        key="charger_state",
        address=130,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:battery-charging-wireless",
        options={
            0: "Not Charging",
            1: "Bulk",
            2: "Absorption",
            3: "Overcharge",
            4: "Equalize",
            5: "Float",
            6: "No Float",
            7: "Constant VI",
            8: "Charger Disabled",
            9: "Qualifying AC",
            10: "Qualifying APS",
        },
    ),
    # --- Heatsink Temperature ---
    ModbusRegisterDefinition(
        name="Heatsink Temperature",
        key="heatsink_temperature",
        address=140,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category="diagnostic",
        icon="mdi:thermometer",
    ),
    # --- Transformer Temperature ---
    ModbusRegisterDefinition(
        name="Transformer Temperature",
        key="transformer_temperature",
        address=142,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category="diagnostic",
        icon="mdi:thermometer",
    ),
]


# --- XW Pro Writable Holding Registers ---
XW_PRO_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = [
    # Switches (on/off)
    ModbusRegisterDefinition(
        name="Inverter Enabled",
        key="inverter_enabled",
        address=150,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:power",
    ),
    ModbusRegisterDefinition(
        name="Charger Enabled",
        key="charger_enabled",
        address=152,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:battery-charging",
    ),
    ModbusRegisterDefinition(
        name="Search Mode Enabled",
        key="search_mode_enabled",
        address=154,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:magnify",
    ),
    ModbusRegisterDefinition(
        name="Grid Support Enabled",
        key="grid_support_enabled",
        address=156,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:transmission-tower",
    ),
    # Selects (modes)
    ModbusRegisterDefinition(
        name="Force Charge Mode",
        key="force_charge_mode",
        address=160,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        options={
            0: "Off",
            1: "Bulk",
            2: "Float",
        },
        icon="mdi:battery-charging-high",
    ),
    ModbusRegisterDefinition(
        name="AC Input Mode",
        key="ac_input_mode",
        address=162,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        options={
            0: "Generator",
            1: "Grid (Support)",
            2: "Grid (Tie / Sell)",
        },
        icon="mdi:power-plug",
    ),
    # Numbers (setpoints)
    ModbusRegisterDefinition(
        name="Absorb Voltage Setpoint",
        key="absorb_voltage_setpoint",
        address=170,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Float Voltage Setpoint",
        key="float_voltage_setpoint",
        address=172,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Max Charge Current",
        key="max_charge_current",
        address=174,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=0,
        max_value=100.0,
        unit=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
    ),
    ModbusRegisterDefinition(
        name="Max AC Input Current",
        key="max_ac_input_current",
        address=176,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=0,
        max_value=60.0,
        unit=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
    ),
    ModbusRegisterDefinition(
        name="Grid Support Voltage",
        key="grid_support_voltage",
        address=178,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:transmission-tower",
    ),
    ModbusRegisterDefinition(
        name="Low Battery Cut Out Voltage",
        key="low_battery_cut_out",
        address=180,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=36.0,
        max_value=56.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:battery-alert",
    ),
    # EPC (External Power Control) commands
    ModbusRegisterDefinition(
        name="EPC Active Power Setpoint",
        key="epc_active_power_setpoint",
        address=200,
        register_type=RegisterType.HOLDING,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        writable=True,
        min_value=-6800,
        max_value=6800,
        unit=UnitOfPower.WATT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="EPC Mode",
        key="epc_mode",
        address=202,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        options={
            0: "Disabled",
            1: "Active Power Control",
            2: "Self-Consumption",
            3: "Load Following",
        },
        icon="mdi:tune",
    ),
]


# =============================================================================
# MPPT CHARGE CONTROLLER REGISTERS (slave default: 170+)
# Based on 503-0252-01-01_RevA.4_Modbus_Map_MPPT80_Device.pdf
# =============================================================================

MPPT_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
    ModbusRegisterDefinition(
        name="Device Status",
        key="device_status",
        address=50,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:state-machine",
        options={
            0: "Sleeping",
            1: "Waking",
            2: "MPPT Tracking",
            3: "Equalizing",
            4: "Absorbing",
            5: "Floating",
            6: "Not Charging",
            7: "Fault",
        },
    ),
    ModbusRegisterDefinition(
        name="Active Faults",
        key="active_faults",
        address=52,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        icon="mdi:alert-circle",
        entity_category="diagnostic",
    ),
    # --- PV Input ---
    ModbusRegisterDefinition(
        name="PV Voltage",
        key="pv_voltage",
        address=60,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=1,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-panel",
    ),
    ModbusRegisterDefinition(
        name="PV Current",
        key="pv_current",
        address=62,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-panel",
    ),
    ModbusRegisterDefinition(
        name="PV Power",
        key="pv_power",
        address=64,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    # --- Battery Output ---
    ModbusRegisterDefinition(
        name="Battery Voltage",
        key="battery_voltage",
        address=70,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    ModbusRegisterDefinition(
        name="Battery Current",
        key="battery_current",
        address=72,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    ModbusRegisterDefinition(
        name="Charge Power",
        key="charge_power",
        address=74,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    ModbusRegisterDefinition(
        name="Charge State",
        key="charge_state",
        address=76,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:battery-charging-wireless",
        options={
            0: "Not Charging",
            1: "Bulk",
            2: "Absorption",
            3: "Float",
            4: "Equalize",
        },
    ),
    # --- Energy Counters ---
    ModbusRegisterDefinition(
        name="Total Energy Harvested",
        key="total_energy_harvested",
        address=80,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:solar-power-variant",
    ),
    ModbusRegisterDefinition(
        name="Daily Energy Harvested",
        key="daily_energy_harvested",
        address=82,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:white-balance-sunny",
    ),
    # --- Temperature ---
    ModbusRegisterDefinition(
        name="Heatsink Temperature",
        key="heatsink_temperature",
        address=90,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category="diagnostic",
        icon="mdi:thermometer",
    ),
]

MPPT_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="MPPT Enabled",
        key="mppt_enabled",
        address=150,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:solar-panel",
    ),
    ModbusRegisterDefinition(
        name="Absorb Voltage Setpoint",
        key="absorb_voltage_setpoint",
        address=160,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Float Voltage Setpoint",
        key="float_voltage_setpoint",
        address=162,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Max Charge Current",
        key="max_charge_current",
        address=164,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=0,
        max_value=80.0,
        unit=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
    ),
]


# =============================================================================
# AGS (AUTOMATIC GENERATOR START) REGISTERS (slave default: 20)
# Based on 503-0247-01-01_RevA.4_Modbus_Map_AGS_Device.pdf
# =============================================================================

AGS_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
    ModbusRegisterDefinition(
        name="AGS Status",
        key="ags_status",
        address=50,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:engine",
        options={
            0: "Generator Off",
            1: "Generator Starting",
            2: "Generator Warmup",
            3: "Generator Running",
            4: "Generator Cooldown",
            5: "Generator Stopping",
            6: "Fault",
        },
    ),
    ModbusRegisterDefinition(
        name="Generator Run Time",
        key="generator_run_time",
        address=52,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfTime.HOURS,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    ModbusRegisterDefinition(
        name="Generator Start Count",
        key="generator_start_count",
        address=54,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        icon="mdi:counter",
        entity_category="diagnostic",
    ),
]

AGS_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Generator Force On",
        key="generator_force_on",
        address=150,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Off", 1: "Force On"},
        icon="mdi:engine",
    ),
    ModbusRegisterDefinition(
        name="AGS Enabled",
        key="ags_enabled",
        address=152,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        writable=True,
        min_value=0,
        max_value=1,
        options={0: "Disabled", 1: "Enabled"},
        icon="mdi:engine",
    ),
    ModbusRegisterDefinition(
        name="Start Voltage Setpoint",
        key="start_voltage_setpoint",
        address=160,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=36.0,
        max_value=56.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Stop Voltage Setpoint",
        key="stop_voltage_setpoint",
        address=162,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=0.1,
        precision=1,
        writable=True,
        min_value=40.0,
        max_value=64.0,
        unit=UnitOfElectricPotential.VOLT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Max Generator Run Time",
        key="max_gen_run_time",
        address=164,
        register_type=RegisterType.HOLDING,
        data_type=DataType.UINT16,
        scale=1.0,
        writable=True,
        min_value=0,
        max_value=24,
        unit=UnitOfTime.HOURS,
        icon="mdi:timer",
    ),
]


# =============================================================================
# BATTERY MONITOR REGISTERS (slave default: 30)
# Based on 503-0261-01-01_RevA.4_Battery_Monitor_Device.pdf
# =============================================================================

BATTERY_MONITOR_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
    ModbusRegisterDefinition(
        name="Battery Voltage",
        key="battery_voltage",
        address=60,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    ModbusRegisterDefinition(
        name="Battery Current",
        key="battery_current",
        address=62,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    ModbusRegisterDefinition(
        name="Battery SOC",
        key="battery_soc",
        address=64,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=1.0,
        precision=0,
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart-variant",
    ),
    ModbusRegisterDefinition(
        name="Battery Temperature",
        key="battery_temperature",
        address=66,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    ModbusRegisterDefinition(
        name="Battery Power",
        key="battery_power",
        address=68,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    ModbusRegisterDefinition(
        name="Days Since Last Full Charge",
        key="days_since_full_charge",
        address=70,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=1.0,
        precision=0,
        unit=UnitOfTime.DAYS,
        icon="mdi:calendar-clock",
    ),
    ModbusRegisterDefinition(
        name="Minimum Battery Voltage",
        key="min_battery_voltage",
        address=72,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category="diagnostic",
        icon="mdi:battery-minus",
    ),
    ModbusRegisterDefinition(
        name="Maximum Battery Voltage",
        key="max_battery_voltage",
        address=74,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category="diagnostic",
        icon="mdi:battery-plus",
    ),
]

BATTERY_MONITOR_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = []


# =============================================================================
# GATEWAY / INSIGHTHOME / INSIGHTFACILITY REGISTERS (slave default: 1)
# Based on IH-IF-Gateway_Modbus-Maps
# =============================================================================

GATEWAY_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
    ModbusRegisterDefinition(
        name="System Status",
        key="system_status",
        address=50,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        icon="mdi:router-wireless",
        options={
            0: "Idle",
            1: "Running",
            2: "Fault",
        },
    ),
    ModbusRegisterDefinition(
        name="Total System PV Power",
        key="total_system_pv_power",
        address=60,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    ModbusRegisterDefinition(
        name="Total System Load Power",
        key="total_system_load_power",
        address=62,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    ModbusRegisterDefinition(
        name="Total System Battery Power",
        key="total_system_battery_power",
        address=64,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    ModbusRegisterDefinition(
        name="Total System Grid Power",
        key="total_system_grid_power",
        address=66,
        register_type=RegisterType.INPUT,
        data_type=DataType.INT32,
        count=2,
        scale=1.0,
        precision=0,
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower",
    ),
    ModbusRegisterDefinition(
        name="System Battery SOC",
        key="system_battery_soc",
        address=68,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        scale=1.0,
        precision=0,
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    ModbusRegisterDefinition(
        name="Number of Connected Devices",
        key="connected_devices_count",
        address=70,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:devices",
    ),
    # --- System Energy Counters ---
    ModbusRegisterDefinition(
        name="Total System PV Energy",
        key="total_system_pv_energy",
        address=80,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:solar-power-variant",
    ),
    ModbusRegisterDefinition(
        name="Total System Grid Import Energy",
        key="total_system_grid_import_energy",
        address=82,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:transmission-tower-import",
    ),
    ModbusRegisterDefinition(
        name="Total System Grid Export Energy",
        key="total_system_grid_export_energy",
        address=84,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:transmission-tower-export",
    ),
    ModbusRegisterDefinition(
        name="Total System Load Energy",
        key="total_system_load_energy",
        address=86,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT32,
        count=2,
        scale=0.001,
        precision=2,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:lightning-bolt",
    ),
]

GATEWAY_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = []


# =============================================================================
# SCP (System Control Panel) REGISTERS (slave default: 40)
# =============================================================================

SCP_SENSOR_REGISTERS: list[ModbusRegisterDefinition] = [
    ModbusRegisterDefinition(
        name="Firmware Version",
        key="firmware_version",
        address=0,
        register_type=RegisterType.INPUT,
        data_type=DataType.UINT16,
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
]

SCP_CONTROL_REGISTERS: list[ModbusRegisterDefinition] = []


# =============================================================================
# REGISTER MAPS BY DEVICE TYPE
# =============================================================================

# Imported here to avoid circular imports (const.py has no dependencies on this file)
from .const import (  # noqa: E402
    DEVICE_TYPE_AGS,
    DEVICE_TYPE_BATTERY_MONITOR,
    DEVICE_TYPE_GATEWAY,
    DEVICE_TYPE_MPPT,
    DEVICE_TYPE_SCP,
    DEVICE_TYPE_XW_PRO,
)

SENSOR_REGISTERS_BY_DEVICE: dict[str, list[ModbusRegisterDefinition]] = {
    DEVICE_TYPE_XW_PRO: XW_PRO_SENSOR_REGISTERS,
    DEVICE_TYPE_MPPT: MPPT_SENSOR_REGISTERS,
    DEVICE_TYPE_AGS: AGS_SENSOR_REGISTERS,
    DEVICE_TYPE_BATTERY_MONITOR: BATTERY_MONITOR_SENSOR_REGISTERS,
    DEVICE_TYPE_GATEWAY: GATEWAY_SENSOR_REGISTERS,
    DEVICE_TYPE_SCP: SCP_SENSOR_REGISTERS,
}

CONTROL_REGISTERS_BY_DEVICE: dict[str, list[ModbusRegisterDefinition]] = {
    DEVICE_TYPE_XW_PRO: XW_PRO_CONTROL_REGISTERS,
    DEVICE_TYPE_MPPT: MPPT_CONTROL_REGISTERS,
    DEVICE_TYPE_AGS: AGS_CONTROL_REGISTERS,
    DEVICE_TYPE_BATTERY_MONITOR: BATTERY_MONITOR_CONTROL_REGISTERS,
    DEVICE_TYPE_GATEWAY: GATEWAY_CONTROL_REGISTERS,
    DEVICE_TYPE_SCP: SCP_CONTROL_REGISTERS,
}
